export const BUSINESS = {
  name: "Roos Garage Doors Cape Town",
  legalName: "Roos Garage Doors Cape Town (Pty) Ltd",
  tagline: "Awesome designs for any opening",
  founded: "2012",
  phone: "+27219818118",
  phoneDisplay: "021 981 8118",
  cell: "+27827886830",
  cellDisplay: "082 788 6830",
  email: "info@roosgaragedoorscapetown.co.za",
  repairEmail: "rgdcptrepairs@gmail.com",
  tradeEmail: "orders@roosgaragedoorscapetown.co.za",
  address: {
    street: "6 Brass Street",
    suburb: "Brackenfell Industria",
    city: "Brackenfell",
    region: "Western Cape",
    postal: "7561",
    country: "ZA",
  },
  geo: { lat: -33.8760, lng: 18.6980 },
  hours: [
    { day: "Mon–Thu", open: "08:00", close: "16:30" },
    { day: "Friday", open: "08:00", close: "15:00" },
    { day: "Sat–Sun", open: "Closed", close: "" },
  ],
  url: "https://roosgaragedoorscapetown.co.za",
  social: { twitter: "https://twitter.com/RGD_CPT" },
};

export const SERVICES = [
  {
    slug: "meranti-timber-garage-doors",
    name: "Meranti Timber Garage Doors",
    short: "Hand-finished meranti hardwood doors, built in Brackenfell.",
    icon: "timber",
    keyword: "meranti garage doors cape town",
    hero: "Warm, solid, and unmistakably real. Meranti timber doors built by hand in our Brackenfell workshop.",
    body: [
      "Meranti is the classic Cape Town garage door: a dense Southeast Asian hardwood that handles our salt air and summer sun better than pine, and carries stain and varnish like furniture. We mill, assemble, and finish every door on site at 6 Brass Street.",
      "Every meranti door we build is cut to the exact opening, squared on the bench, and sanded by hand before finishing. You choose the panel layout — horizontal slatted, raised panel, cathedral, or custom — and we match the grain across the face so it reads as one piece when closed.",
      "Because we manufacture in-house, non-standard sizes and shapes cost what a standard door costs elsewhere. Arched openings, double-width sectionals, and heritage replacements are routine work for us.",
    ],
    features: [
      "Kiln-dried SA-graded meranti hardwood",
      "Sectional overhead or tip-up mechanisms",
      "Custom sizes, panels, and grain layouts",
      "Factory or on-site varnish & seal",
      "Matching pedestrian doors on request",
      "10-year structural workshop guarantee",
    ],
    cta: "Quote my meranti door",
  },
  {
    slug: "aluminium-garage-doors",
    name: "Aluminium Garage Doors",
    short: "Lightweight, low-maintenance, coastal-proof.",
    icon: "aluminium",
    keyword: "aluminium garage doors cape town",
    hero: "Salt, wind, and sun make short work of steel on the Cape coast. Aluminium doesn't care.",
    body: [
      "Our aluminium doors are the smart call for Atlantic Seaboard, False Bay, and West Coast homes where corrosion eats ordinary steel doors in three to five years. Aluminium won't rust, stays light on the motor, and holds a powder-coat finish for decades.",
      "Choose smooth or stucco-textured panels, in any RAL colour, with matching hardware. The sections ride on sealed nylon rollers so the operation stays quiet and smooth through wet winters.",
      "Paired with an Eazylift operator, an aluminium door is effectively fit-and-forget — a wipe-down twice a year and it still looks like it did on install day.",
    ],
    features: [
      "Smooth or stucco-finish panels",
      "Any RAL powder-coat colour",
      "Corrosion-proof — ideal for coastal homes",
      "Lighter than steel = longer motor life",
      "Sectional overhead design",
      "Tinted window inserts available",
    ],
    cta: "Quote my aluminium door",
  },
  {
    slug: "aluzinc-steel-garage-doors",
    name: "Aluzinc Steel Garage Doors",
    short: "Affordable stucco-finish steel, built to last.",
    icon: "steel",
    keyword: "steel garage doors cape town",
    hero: "Aluzinc — the workhorse finish. Strong, sharp-looking, and a real budget win.",
    body: [
      "Aluzinc is hot-dip steel coated with an aluminium-zinc alloy that dramatically outlasts plain galvanised sheet. For inland Cape Town suburbs it's the price-to-performance winner: the look of a solid steel door, the longevity of a far more expensive finish.",
      "We supply and install Aluzinc in stucco-embossed panels — the textured finish hides scuffs, knocks, and road grit far better than a smooth face, which matters on daily-use residential doors.",
      "Built sectional and overhead by default. Hardware, tracks, and springs are balanced for the specific door weight, so it rides smoothly on a residential or commercial-duty motor.",
    ],
    features: [
      "Aluzinc-coated steel panels",
      "Stucco-embossed texture",
      "Excellent corrosion resistance inland",
      "Sectional overhead mechanism",
      "Powder-coat colour options",
      "Best price-to-durability ratio in the range",
    ],
    cta: "Quote my steel door",
  },
  {
    slug: "garage-door-automation",
    name: "Eazylift Garage Door Automation",
    short: "Sole Cape Town supplier of the Eazylift opener range.",
    icon: "motor",
    keyword: "garage door motors cape town",
    hero: "The operator makes or breaks a door. We only fit Eazylift.",
    body: [
      "Roos Garage Doors Cape Town is the sole supplier and installer of Eazylift operators in the region. We fit them because they're quiet, they hold the door square on every cycle, and the parts are stocked on our shelves — not imported and waiting.",
      "Every automation install includes the operator, rails, brackets, remote handsets, wiring to your existing power, battery backup option, and the safety sensors required by SANS code. We set up each door's soft-start and soft-stop individually so the motor runs for years instead of burning out on slam cycles.",
      "Existing door that never got automated? We'll come out, measure, confirm it's balanced correctly, and fit an Eazylift in under half a day.",
    ],
    features: [
      "Eazylift sole-supplier in Cape Town",
      "Soft-start / soft-stop calibration",
      "Battery backup option for load-shedding",
      "Safety sensors fitted to SANS code",
      "Remote handsets + wall button included",
      "Retrofits to existing doors",
    ],
    cta: "Book an automation fit",
  },
  {
    slug: "repairs",
    name: "Garage Door Repairs & Servicing",
    short: "Same-week callouts across the Cape Town metro.",
    icon: "wrench",
    keyword: "garage door repairs cape town",
    hero: "Door stuck open? Motor grinding? Spring gone? We'll get you moving.",
    body: [
      "Our repair line runs out of the same Brackenfell workshop as our manufacturing, which means the parts and the people are in one place. When you phone in, the tech you speak to is the tech coming to your site — no middle layer, no handover, no guesswork.",
      "Most callouts are solved on the first visit: cable replacement, torsion spring swap, track realignment, roller replacement, motor board diagnosis, remote re-pairing, or full operator swap-outs. We carry common parts in the van.",
      "If your door is an old model we didn't build, that's fine — we repair any brand of sectional or tip-up residential door. If it can't be economically saved we'll tell you upfront and quote a replacement instead.",
    ],
    features: [
      "Same-week metro callouts",
      "Torsion spring replacement",
      "Cables, rollers, tracks, brackets",
      "Operator diagnosis & replacement",
      "Remote re-pairing and re-code",
      "Works on any brand of door",
    ],
    cta: "Book a repair",
  },
];

export const AREAS = [
  "Brackenfell", "Bellville", "Durbanville", "Kuils River", "Stellenbosch",
  "Somerset West", "Gordon's Bay", "Strand", "Helderberg",
  "Claremont", "Constantia", "Tokai", "Southern Suburbs",
  "Sea Point", "Camps Bay", "Atlantic Seaboard", "Green Point",
  "Milnerton", "Table View", "Blouberg", "West Coast",
];

export const TESTIMONIALS = [
  { quote: "Thank you very much for sorting out the issues with my door. I will recommend you to all my friends and family.", author: "Richard", location: "Bantry Bay" },
  { quote: "Besides the great service and competitive price, you also have an excellent product.", author: "Mr. La Meyer", location: "Forest Heights" },
  { quote: "Quoted on Monday, fitted on Thursday. The meranti door looks like a piece of furniture — neighbours keep asking who did it.", author: "S. Pretorius", location: "Durbanville" },
];
